# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


# Fastfile

plugins = [
  "fastlane-plugin-increment_version_code"
]

default_platform(:android)
  before_all do
    Dotenv.load ".env"
  end
desc "Verify Build for Android"
lane :test_android_build do
  load_dotenv
  debug_keystore = ENV['DEBUG_KEYSTORE']
  debug_keystore_alias = ENV['DEBUG_KEYSTORE_ALIAS']
  debug_keystore_password = ENV['DEBUG_KEYSTORE_PASSWORD']

  gradle(
    task: "assembleNewlogicDebug",
    properties: {
      'DEBUG_KEYSTORE' => debug_keystore,
      'DEBUG_KEYSTORE_ALIAS' => debug_keystore_alias,
      'DEBUG_KEYSTORE_PASSWORD' => debug_keystore_password
    }
  )
end

desc "Build Android and increase version code"
lane :build_android do
  # increment_version_code(
  #   gradle_file_path: "./app/build.gradle",
  # )
  gradle(
    task: "assembleNewlogicRelease",
  )
end




#   desc "Increment version name"
#   lane :increment_vname do
#   increment_version_name(
#        gradle_file_path: "./app/build.gradle",
#  )
#   end