default_platform(:android)

MIMOTO_HOST = ENV["MIMOTO_HOST"]
APPLICATION_THEME = ENV["APPLICATION_THEME"]
RELEASE_KEYSTORE_ALIAS = ENV["RELEASE_KEYSTORE_ALIAS"]
RELEASE_KEYSTORE_PASSWORD = ENV["RELEASE_KEYSTORE_PASSWORD"]
PLAY_CONSOLE_RELEASE_DESCRIPTION = ENV["PLAY_CONSOLE_RELEASE_DESCRIPTION"]

desc "Verify Build for Android"
lane :android_build do
  gradle(
    task: "assembleNewlogicDebug",
  )
end

desc "Deploy a alpha version to the Google Play"
lane :android_build_alpha do
    gradle(task: "clean bundleMosipRelease")
    upload_to_play_store(
    track: 'internal',
    release_status: 'draft',
    release_name: 'Inji 0.8',
    release_notes: {
      'en-US': "#{PLAY_CONSOLE_RELEASE_DESCRIPTION}",
    },
    testers: 'CI-test'
  )
end

